version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  spa:
    hostname: localhost
    build: spa
    ports:
      - "8092:80"
  
  scoring:
    build: scoring
    ports:
      - "3001:3000"
    environment:
      - MONGO_URI=mongodb://database:27017
      - DBNAME=db
    depends_on:
      - database

  evaluation:
    build: evaluation
    ports:
      - "3002:3000"
    environment:
      - MONGO_URI=mongodb://database:27017
      - SCORING_URI=http://scoring:3000
      - DBNAME=db
    depends_on:
      - database
      - scoring

  database:
    image: mongo
    ports:
      - "27017:27017"
  seed:
    image: curlimages/curl
    depends_on:
      - scoring
      - evaluation
    depends_on:
      - scoring
      - evaluation
    restart: "no"
    entrypoint: [ "sh", "-c", "sleep 2 && curl http://scoring:3000/seed && curl http://evaluation:3000/seed"]